# Generated by Django 6.0.4 on 2026-04-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=30)),
            ],
        ),
    ]
